/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum Status implements org.apache.thrift.TEnum {
  NOT_STARTED(1),
  IN_PROGRESS(2),
  COMPLETED(3),
  ROLLING_BACK(4),
  ROLLED_BACK(5);

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static Status findByValue(int value) { 
    switch (value) {
      case 1:
        return NOT_STARTED;
      case 2:
        return IN_PROGRESS;
      case 3:
        return COMPLETED;
      case 4:
        return ROLLING_BACK;
      case 5:
        return ROLLED_BACK;
      default:
        return null;
    }
  }
}
