// Autogenerated by Thrift Compiler (0.9.3)
// DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING

package scoot

import (
	"bytes"
	"fmt"
	"github.com/apache/thrift/lib/go/thrift"
	"github.com/twitter/scoot/bazel/execution/bazelapi/gen-go/bazel"
)

// (needed to ensure safety because of naive import list construction.)
var _ = thrift.ZERO
var _ = fmt.Printf
var _ = bytes.Equal

var _ = bazel.GoUnusedProtection__

type CloudScoot interface {
	// Parameters:
	//  - Job
	RunJob(job *JobDefinition) (r *JobId, err error)
	// Parameters:
	//  - JobId
	GetStatus(jobId string) (r *JobStatus, err error)
	// Parameters:
	//  - JobId
	KillJob(jobId string) (r *JobStatus, err error)
	// Parameters:
	//  - Req
	OfflineWorker(req *OfflineWorkerReq) (err error)
	// Parameters:
	//  - Req
	ReinstateWorker(req *ReinstateWorkerReq) (err error)
	GetSchedulerStatus() (r *SchedulerStatus, err error)
	// Parameters:
	//  - MaxTasks
	ThrottleScheduler(maxTasks int32) (err error)
}

type CloudScootClient struct {
	Transport       thrift.TTransport
	ProtocolFactory thrift.TProtocolFactory
	InputProtocol   thrift.TProtocol
	OutputProtocol  thrift.TProtocol
	SeqId           int32
}

func NewCloudScootClientFactory(t thrift.TTransport, f thrift.TProtocolFactory) *CloudScootClient {
	return &CloudScootClient{Transport: t,
		ProtocolFactory: f,
		InputProtocol:   f.GetProtocol(t),
		OutputProtocol:  f.GetProtocol(t),
		SeqId:           0,
	}
}

func NewCloudScootClientProtocol(t thrift.TTransport, iprot thrift.TProtocol, oprot thrift.TProtocol) *CloudScootClient {
	return &CloudScootClient{Transport: t,
		ProtocolFactory: nil,
		InputProtocol:   iprot,
		OutputProtocol:  oprot,
		SeqId:           0,
	}
}

// Parameters:
//  - Job
func (p *CloudScootClient) RunJob(job *JobDefinition) (r *JobId, err error) {
	if err = p.sendRunJob(job); err != nil {
		return
	}
	return p.recvRunJob()
}

func (p *CloudScootClient) sendRunJob(job *JobDefinition) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("RunJob", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := CloudScootRunJobArgs{
		Job: job,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *CloudScootClient) recvRunJob() (value *JobId, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "RunJob" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "RunJob failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "RunJob failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error8 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error9 error
		error9, err = error8.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error9
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "RunJob failed: invalid message type")
		return
	}
	result := CloudScootRunJobResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	if result.Ir != nil {
		err = result.Ir
		return
	} else if result.Cnsn != nil {
		err = result.Cnsn
		return
	}
	value = result.GetSuccess()
	return
}

// Parameters:
//  - JobId
func (p *CloudScootClient) GetStatus(jobId string) (r *JobStatus, err error) {
	if err = p.sendGetStatus(jobId); err != nil {
		return
	}
	return p.recvGetStatus()
}

func (p *CloudScootClient) sendGetStatus(jobId string) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("GetStatus", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := CloudScootGetStatusArgs{
		JobId: jobId,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *CloudScootClient) recvGetStatus() (value *JobStatus, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "GetStatus" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "GetStatus failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "GetStatus failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error10 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error11 error
		error11, err = error10.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error11
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "GetStatus failed: invalid message type")
		return
	}
	result := CloudScootGetStatusResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	if result.Ir != nil {
		err = result.Ir
		return
	} else if result.Err != nil {
		err = result.Err
		return
	}
	value = result.GetSuccess()
	return
}

// Parameters:
//  - JobId
func (p *CloudScootClient) KillJob(jobId string) (r *JobStatus, err error) {
	if err = p.sendKillJob(jobId); err != nil {
		return
	}
	return p.recvKillJob()
}

func (p *CloudScootClient) sendKillJob(jobId string) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("KillJob", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := CloudScootKillJobArgs{
		JobId: jobId,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *CloudScootClient) recvKillJob() (value *JobStatus, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "KillJob" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "KillJob failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "KillJob failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error12 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error13 error
		error13, err = error12.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error13
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "KillJob failed: invalid message type")
		return
	}
	result := CloudScootKillJobResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	if result.Ir != nil {
		err = result.Ir
		return
	} else if result.Err != nil {
		err = result.Err
		return
	}
	value = result.GetSuccess()
	return
}

// Parameters:
//  - Req
func (p *CloudScootClient) OfflineWorker(req *OfflineWorkerReq) (err error) {
	if err = p.sendOfflineWorker(req); err != nil {
		return
	}
	return p.recvOfflineWorker()
}

func (p *CloudScootClient) sendOfflineWorker(req *OfflineWorkerReq) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("OfflineWorker", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := CloudScootOfflineWorkerArgs{
		Req: req,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *CloudScootClient) recvOfflineWorker() (err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "OfflineWorker" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "OfflineWorker failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "OfflineWorker failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error14 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error15 error
		error15, err = error14.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error15
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "OfflineWorker failed: invalid message type")
		return
	}
	result := CloudScootOfflineWorkerResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	if result.Ir != nil {
		err = result.Ir
		return
	} else if result.Err != nil {
		err = result.Err
		return
	}
	return
}

// Parameters:
//  - Req
func (p *CloudScootClient) ReinstateWorker(req *ReinstateWorkerReq) (err error) {
	if err = p.sendReinstateWorker(req); err != nil {
		return
	}
	return p.recvReinstateWorker()
}

func (p *CloudScootClient) sendReinstateWorker(req *ReinstateWorkerReq) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("ReinstateWorker", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := CloudScootReinstateWorkerArgs{
		Req: req,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *CloudScootClient) recvReinstateWorker() (err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "ReinstateWorker" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "ReinstateWorker failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "ReinstateWorker failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error16 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error17 error
		error17, err = error16.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error17
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "ReinstateWorker failed: invalid message type")
		return
	}
	result := CloudScootReinstateWorkerResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	if result.Ir != nil {
		err = result.Ir
		return
	} else if result.Err != nil {
		err = result.Err
		return
	}
	return
}

func (p *CloudScootClient) GetSchedulerStatus() (r *SchedulerStatus, err error) {
	if err = p.sendGetSchedulerStatus(); err != nil {
		return
	}
	return p.recvGetSchedulerStatus()
}

func (p *CloudScootClient) sendGetSchedulerStatus() (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("GetSchedulerStatus", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := CloudScootGetSchedulerStatusArgs{}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *CloudScootClient) recvGetSchedulerStatus() (value *SchedulerStatus, err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "GetSchedulerStatus" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "GetSchedulerStatus failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "GetSchedulerStatus failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error18 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error19 error
		error19, err = error18.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error19
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "GetSchedulerStatus failed: invalid message type")
		return
	}
	result := CloudScootGetSchedulerStatusResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	if result.Err != nil {
		err = result.Err
		return
	}
	value = result.GetSuccess()
	return
}

// Parameters:
//  - MaxTasks
func (p *CloudScootClient) ThrottleScheduler(maxTasks int32) (err error) {
	if err = p.sendThrottleScheduler(maxTasks); err != nil {
		return
	}
	return p.recvThrottleScheduler()
}

func (p *CloudScootClient) sendThrottleScheduler(maxTasks int32) (err error) {
	oprot := p.OutputProtocol
	if oprot == nil {
		oprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.OutputProtocol = oprot
	}
	p.SeqId++
	if err = oprot.WriteMessageBegin("ThrottleScheduler", thrift.CALL, p.SeqId); err != nil {
		return
	}
	args := CloudScootThrottleSchedulerArgs{
		MaxTasks: maxTasks,
	}
	if err = args.Write(oprot); err != nil {
		return
	}
	if err = oprot.WriteMessageEnd(); err != nil {
		return
	}
	return oprot.Flush()
}

func (p *CloudScootClient) recvThrottleScheduler() (err error) {
	iprot := p.InputProtocol
	if iprot == nil {
		iprot = p.ProtocolFactory.GetProtocol(p.Transport)
		p.InputProtocol = iprot
	}
	method, mTypeId, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return
	}
	if method != "ThrottleScheduler" {
		err = thrift.NewTApplicationException(thrift.WRONG_METHOD_NAME, "ThrottleScheduler failed: wrong method name")
		return
	}
	if p.SeqId != seqId {
		err = thrift.NewTApplicationException(thrift.BAD_SEQUENCE_ID, "ThrottleScheduler failed: out of sequence response")
		return
	}
	if mTypeId == thrift.EXCEPTION {
		error20 := thrift.NewTApplicationException(thrift.UNKNOWN_APPLICATION_EXCEPTION, "Unknown Exception")
		var error21 error
		error21, err = error20.Read(iprot)
		if err != nil {
			return
		}
		if err = iprot.ReadMessageEnd(); err != nil {
			return
		}
		err = error21
		return
	}
	if mTypeId != thrift.REPLY {
		err = thrift.NewTApplicationException(thrift.INVALID_MESSAGE_TYPE_EXCEPTION, "ThrottleScheduler failed: invalid message type")
		return
	}
	result := CloudScootThrottleSchedulerResult{}
	if err = result.Read(iprot); err != nil {
		return
	}
	if err = iprot.ReadMessageEnd(); err != nil {
		return
	}
	if result.Ir != nil {
		err = result.Ir
		return
	} else if result.Err != nil {
		err = result.Err
		return
	}
	return
}

type CloudScootProcessor struct {
	processorMap map[string]thrift.TProcessorFunction
	handler      CloudScoot
}

func (p *CloudScootProcessor) AddToProcessorMap(key string, processor thrift.TProcessorFunction) {
	p.processorMap[key] = processor
}

func (p *CloudScootProcessor) GetProcessorFunction(key string) (processor thrift.TProcessorFunction, ok bool) {
	processor, ok = p.processorMap[key]
	return processor, ok
}

func (p *CloudScootProcessor) ProcessorMap() map[string]thrift.TProcessorFunction {
	return p.processorMap
}

func NewCloudScootProcessor(handler CloudScoot) *CloudScootProcessor {

	self22 := &CloudScootProcessor{handler: handler, processorMap: make(map[string]thrift.TProcessorFunction)}
	self22.processorMap["RunJob"] = &cloudScootProcessorRunJob{handler: handler}
	self22.processorMap["GetStatus"] = &cloudScootProcessorGetStatus{handler: handler}
	self22.processorMap["KillJob"] = &cloudScootProcessorKillJob{handler: handler}
	self22.processorMap["OfflineWorker"] = &cloudScootProcessorOfflineWorker{handler: handler}
	self22.processorMap["ReinstateWorker"] = &cloudScootProcessorReinstateWorker{handler: handler}
	self22.processorMap["GetSchedulerStatus"] = &cloudScootProcessorGetSchedulerStatus{handler: handler}
	self22.processorMap["ThrottleScheduler"] = &cloudScootProcessorThrottleScheduler{handler: handler}
	return self22
}

func (p *CloudScootProcessor) Process(iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	name, _, seqId, err := iprot.ReadMessageBegin()
	if err != nil {
		return false, err
	}
	if processor, ok := p.GetProcessorFunction(name); ok {
		return processor.Process(seqId, iprot, oprot)
	}
	iprot.Skip(thrift.STRUCT)
	iprot.ReadMessageEnd()
	x23 := thrift.NewTApplicationException(thrift.UNKNOWN_METHOD, "Unknown function "+name)
	oprot.WriteMessageBegin(name, thrift.EXCEPTION, seqId)
	x23.Write(oprot)
	oprot.WriteMessageEnd()
	oprot.Flush()
	return false, x23

}

type cloudScootProcessorRunJob struct {
	handler CloudScoot
}

func (p *cloudScootProcessorRunJob) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := CloudScootRunJobArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("RunJob", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := CloudScootRunJobResult{}
	var retval *JobId
	var err2 error
	if retval, err2 = p.handler.RunJob(args.Job); err2 != nil {
		switch v := err2.(type) {
		case *InvalidRequest:
			result.Ir = v
		case *CanNotScheduleNow:
			result.Cnsn = v
		default:
			x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing RunJob: "+err2.Error())
			oprot.WriteMessageBegin("RunJob", thrift.EXCEPTION, seqId)
			x.Write(oprot)
			oprot.WriteMessageEnd()
			oprot.Flush()
			return true, err2
		}
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("RunJob", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type cloudScootProcessorGetStatus struct {
	handler CloudScoot
}

func (p *cloudScootProcessorGetStatus) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := CloudScootGetStatusArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("GetStatus", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := CloudScootGetStatusResult{}
	var retval *JobStatus
	var err2 error
	if retval, err2 = p.handler.GetStatus(args.JobId); err2 != nil {
		switch v := err2.(type) {
		case *InvalidRequest:
			result.Ir = v
		case *ScootServerError:
			result.Err = v
		default:
			x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetStatus: "+err2.Error())
			oprot.WriteMessageBegin("GetStatus", thrift.EXCEPTION, seqId)
			x.Write(oprot)
			oprot.WriteMessageEnd()
			oprot.Flush()
			return true, err2
		}
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("GetStatus", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type cloudScootProcessorKillJob struct {
	handler CloudScoot
}

func (p *cloudScootProcessorKillJob) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := CloudScootKillJobArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("KillJob", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := CloudScootKillJobResult{}
	var retval *JobStatus
	var err2 error
	if retval, err2 = p.handler.KillJob(args.JobId); err2 != nil {
		switch v := err2.(type) {
		case *InvalidRequest:
			result.Ir = v
		case *ScootServerError:
			result.Err = v
		default:
			x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing KillJob: "+err2.Error())
			oprot.WriteMessageBegin("KillJob", thrift.EXCEPTION, seqId)
			x.Write(oprot)
			oprot.WriteMessageEnd()
			oprot.Flush()
			return true, err2
		}
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("KillJob", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type cloudScootProcessorOfflineWorker struct {
	handler CloudScoot
}

func (p *cloudScootProcessorOfflineWorker) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := CloudScootOfflineWorkerArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("OfflineWorker", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := CloudScootOfflineWorkerResult{}
	var err2 error
	if err2 = p.handler.OfflineWorker(args.Req); err2 != nil {
		switch v := err2.(type) {
		case *InvalidRequest:
			result.Ir = v
		case *ScootServerError:
			result.Err = v
		default:
			x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing OfflineWorker: "+err2.Error())
			oprot.WriteMessageBegin("OfflineWorker", thrift.EXCEPTION, seqId)
			x.Write(oprot)
			oprot.WriteMessageEnd()
			oprot.Flush()
			return true, err2
		}
	}
	if err2 = oprot.WriteMessageBegin("OfflineWorker", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type cloudScootProcessorReinstateWorker struct {
	handler CloudScoot
}

func (p *cloudScootProcessorReinstateWorker) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := CloudScootReinstateWorkerArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("ReinstateWorker", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := CloudScootReinstateWorkerResult{}
	var err2 error
	if err2 = p.handler.ReinstateWorker(args.Req); err2 != nil {
		switch v := err2.(type) {
		case *InvalidRequest:
			result.Ir = v
		case *ScootServerError:
			result.Err = v
		default:
			x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing ReinstateWorker: "+err2.Error())
			oprot.WriteMessageBegin("ReinstateWorker", thrift.EXCEPTION, seqId)
			x.Write(oprot)
			oprot.WriteMessageEnd()
			oprot.Flush()
			return true, err2
		}
	}
	if err2 = oprot.WriteMessageBegin("ReinstateWorker", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type cloudScootProcessorGetSchedulerStatus struct {
	handler CloudScoot
}

func (p *cloudScootProcessorGetSchedulerStatus) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := CloudScootGetSchedulerStatusArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("GetSchedulerStatus", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := CloudScootGetSchedulerStatusResult{}
	var retval *SchedulerStatus
	var err2 error
	if retval, err2 = p.handler.GetSchedulerStatus(); err2 != nil {
		switch v := err2.(type) {
		case *ScootServerError:
			result.Err = v
		default:
			x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing GetSchedulerStatus: "+err2.Error())
			oprot.WriteMessageBegin("GetSchedulerStatus", thrift.EXCEPTION, seqId)
			x.Write(oprot)
			oprot.WriteMessageEnd()
			oprot.Flush()
			return true, err2
		}
	} else {
		result.Success = retval
	}
	if err2 = oprot.WriteMessageBegin("GetSchedulerStatus", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

type cloudScootProcessorThrottleScheduler struct {
	handler CloudScoot
}

func (p *cloudScootProcessorThrottleScheduler) Process(seqId int32, iprot, oprot thrift.TProtocol) (success bool, err thrift.TException) {
	args := CloudScootThrottleSchedulerArgs{}
	if err = args.Read(iprot); err != nil {
		iprot.ReadMessageEnd()
		x := thrift.NewTApplicationException(thrift.PROTOCOL_ERROR, err.Error())
		oprot.WriteMessageBegin("ThrottleScheduler", thrift.EXCEPTION, seqId)
		x.Write(oprot)
		oprot.WriteMessageEnd()
		oprot.Flush()
		return false, err
	}

	iprot.ReadMessageEnd()
	result := CloudScootThrottleSchedulerResult{}
	var err2 error
	if err2 = p.handler.ThrottleScheduler(args.MaxTasks); err2 != nil {
		switch v := err2.(type) {
		case *InvalidRequest:
			result.Ir = v
		case *ScootServerError:
			result.Err = v
		default:
			x := thrift.NewTApplicationException(thrift.INTERNAL_ERROR, "Internal error processing ThrottleScheduler: "+err2.Error())
			oprot.WriteMessageBegin("ThrottleScheduler", thrift.EXCEPTION, seqId)
			x.Write(oprot)
			oprot.WriteMessageEnd()
			oprot.Flush()
			return true, err2
		}
	}
	if err2 = oprot.WriteMessageBegin("ThrottleScheduler", thrift.REPLY, seqId); err2 != nil {
		err = err2
	}
	if err2 = result.Write(oprot); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.WriteMessageEnd(); err == nil && err2 != nil {
		err = err2
	}
	if err2 = oprot.Flush(); err == nil && err2 != nil {
		err = err2
	}
	if err != nil {
		return
	}
	return true, err
}

// HELPER FUNCTIONS AND STRUCTURES

// Attributes:
//  - Job
type CloudScootRunJobArgs struct {
	Job *JobDefinition `thrift:"job,1" json:"job"`
}

func NewCloudScootRunJobArgs() *CloudScootRunJobArgs {
	return &CloudScootRunJobArgs{}
}

var CloudScootRunJobArgs_Job_DEFAULT *JobDefinition

func (p *CloudScootRunJobArgs) GetJob() *JobDefinition {
	if !p.IsSetJob() {
		return CloudScootRunJobArgs_Job_DEFAULT
	}
	return p.Job
}
func (p *CloudScootRunJobArgs) IsSetJob() bool {
	return p.Job != nil
}

func (p *CloudScootRunJobArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootRunJobArgs) readField1(iprot thrift.TProtocol) error {
	p.Job = &JobDefinition{}
	if err := p.Job.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Job), err)
	}
	return nil
}

func (p *CloudScootRunJobArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("RunJob_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootRunJobArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("job", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:job: ", p), err)
	}
	if err := p.Job.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Job), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:job: ", p), err)
	}
	return err
}

func (p *CloudScootRunJobArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootRunJobArgs(%+v)", *p)
}

// Attributes:
//  - Success
//  - Ir
//  - Cnsn
type CloudScootRunJobResult struct {
	Success *JobId             `thrift:"success,0" json:"success,omitempty"`
	Ir      *InvalidRequest    `thrift:"ir,1" json:"ir,omitempty"`
	Cnsn    *CanNotScheduleNow `thrift:"cnsn,2" json:"cnsn,omitempty"`
}

func NewCloudScootRunJobResult() *CloudScootRunJobResult {
	return &CloudScootRunJobResult{}
}

var CloudScootRunJobResult_Success_DEFAULT *JobId

func (p *CloudScootRunJobResult) GetSuccess() *JobId {
	if !p.IsSetSuccess() {
		return CloudScootRunJobResult_Success_DEFAULT
	}
	return p.Success
}

var CloudScootRunJobResult_Ir_DEFAULT *InvalidRequest

func (p *CloudScootRunJobResult) GetIr() *InvalidRequest {
	if !p.IsSetIr() {
		return CloudScootRunJobResult_Ir_DEFAULT
	}
	return p.Ir
}

var CloudScootRunJobResult_Cnsn_DEFAULT *CanNotScheduleNow

func (p *CloudScootRunJobResult) GetCnsn() *CanNotScheduleNow {
	if !p.IsSetCnsn() {
		return CloudScootRunJobResult_Cnsn_DEFAULT
	}
	return p.Cnsn
}
func (p *CloudScootRunJobResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CloudScootRunJobResult) IsSetIr() bool {
	return p.Ir != nil
}

func (p *CloudScootRunJobResult) IsSetCnsn() bool {
	return p.Cnsn != nil
}

func (p *CloudScootRunJobResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.readField0(iprot); err != nil {
				return err
			}
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootRunJobResult) readField0(iprot thrift.TProtocol) error {
	p.Success = &JobId{}
	if err := p.Success.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *CloudScootRunJobResult) readField1(iprot thrift.TProtocol) error {
	p.Ir = &InvalidRequest{}
	if err := p.Ir.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Ir), err)
	}
	return nil
}

func (p *CloudScootRunJobResult) readField2(iprot thrift.TProtocol) error {
	p.Cnsn = &CanNotScheduleNow{}
	if err := p.Cnsn.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Cnsn), err)
	}
	return nil
}

func (p *CloudScootRunJobResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("RunJob_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootRunJobResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *CloudScootRunJobResult) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetIr() {
		if err := oprot.WriteFieldBegin("ir", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ir: ", p), err)
		}
		if err := p.Ir.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Ir), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ir: ", p), err)
		}
	}
	return err
}

func (p *CloudScootRunJobResult) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetCnsn() {
		if err := oprot.WriteFieldBegin("cnsn", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:cnsn: ", p), err)
		}
		if err := p.Cnsn.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Cnsn), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:cnsn: ", p), err)
		}
	}
	return err
}

func (p *CloudScootRunJobResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootRunJobResult(%+v)", *p)
}

// Attributes:
//  - JobId
type CloudScootGetStatusArgs struct {
	JobId string `thrift:"jobId,1" json:"jobId"`
}

func NewCloudScootGetStatusArgs() *CloudScootGetStatusArgs {
	return &CloudScootGetStatusArgs{}
}

func (p *CloudScootGetStatusArgs) GetJobId() string {
	return p.JobId
}
func (p *CloudScootGetStatusArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootGetStatusArgs) readField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.JobId = v
	}
	return nil
}

func (p *CloudScootGetStatusArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetStatus_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootGetStatusArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("jobId", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:jobId: ", p), err)
	}
	if err := oprot.WriteString(string(p.JobId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.jobId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:jobId: ", p), err)
	}
	return err
}

func (p *CloudScootGetStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootGetStatusArgs(%+v)", *p)
}

// Attributes:
//  - Success
//  - Ir
//  - Err
type CloudScootGetStatusResult struct {
	Success *JobStatus        `thrift:"success,0" json:"success,omitempty"`
	Ir      *InvalidRequest   `thrift:"ir,1" json:"ir,omitempty"`
	Err     *ScootServerError `thrift:"err,2" json:"err,omitempty"`
}

func NewCloudScootGetStatusResult() *CloudScootGetStatusResult {
	return &CloudScootGetStatusResult{}
}

var CloudScootGetStatusResult_Success_DEFAULT *JobStatus

func (p *CloudScootGetStatusResult) GetSuccess() *JobStatus {
	if !p.IsSetSuccess() {
		return CloudScootGetStatusResult_Success_DEFAULT
	}
	return p.Success
}

var CloudScootGetStatusResult_Ir_DEFAULT *InvalidRequest

func (p *CloudScootGetStatusResult) GetIr() *InvalidRequest {
	if !p.IsSetIr() {
		return CloudScootGetStatusResult_Ir_DEFAULT
	}
	return p.Ir
}

var CloudScootGetStatusResult_Err_DEFAULT *ScootServerError

func (p *CloudScootGetStatusResult) GetErr() *ScootServerError {
	if !p.IsSetErr() {
		return CloudScootGetStatusResult_Err_DEFAULT
	}
	return p.Err
}
func (p *CloudScootGetStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CloudScootGetStatusResult) IsSetIr() bool {
	return p.Ir != nil
}

func (p *CloudScootGetStatusResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *CloudScootGetStatusResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.readField0(iprot); err != nil {
				return err
			}
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootGetStatusResult) readField0(iprot thrift.TProtocol) error {
	p.Success = &JobStatus{}
	if err := p.Success.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *CloudScootGetStatusResult) readField1(iprot thrift.TProtocol) error {
	p.Ir = &InvalidRequest{}
	if err := p.Ir.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Ir), err)
	}
	return nil
}

func (p *CloudScootGetStatusResult) readField2(iprot thrift.TProtocol) error {
	p.Err = &ScootServerError{}
	if err := p.Err.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Err), err)
	}
	return nil
}

func (p *CloudScootGetStatusResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetStatus_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootGetStatusResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *CloudScootGetStatusResult) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetIr() {
		if err := oprot.WriteFieldBegin("ir", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ir: ", p), err)
		}
		if err := p.Ir.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Ir), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ir: ", p), err)
		}
	}
	return err
}

func (p *CloudScootGetStatusResult) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetErr() {
		if err := oprot.WriteFieldBegin("err", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:err: ", p), err)
		}
		if err := p.Err.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Err), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:err: ", p), err)
		}
	}
	return err
}

func (p *CloudScootGetStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootGetStatusResult(%+v)", *p)
}

// Attributes:
//  - JobId
type CloudScootKillJobArgs struct {
	JobId string `thrift:"jobId,1" json:"jobId"`
}

func NewCloudScootKillJobArgs() *CloudScootKillJobArgs {
	return &CloudScootKillJobArgs{}
}

func (p *CloudScootKillJobArgs) GetJobId() string {
	return p.JobId
}
func (p *CloudScootKillJobArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootKillJobArgs) readField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.JobId = v
	}
	return nil
}

func (p *CloudScootKillJobArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("KillJob_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootKillJobArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("jobId", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:jobId: ", p), err)
	}
	if err := oprot.WriteString(string(p.JobId)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.jobId (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:jobId: ", p), err)
	}
	return err
}

func (p *CloudScootKillJobArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootKillJobArgs(%+v)", *p)
}

// Attributes:
//  - Success
//  - Ir
//  - Err
type CloudScootKillJobResult struct {
	Success *JobStatus        `thrift:"success,0" json:"success,omitempty"`
	Ir      *InvalidRequest   `thrift:"ir,1" json:"ir,omitempty"`
	Err     *ScootServerError `thrift:"err,2" json:"err,omitempty"`
}

func NewCloudScootKillJobResult() *CloudScootKillJobResult {
	return &CloudScootKillJobResult{}
}

var CloudScootKillJobResult_Success_DEFAULT *JobStatus

func (p *CloudScootKillJobResult) GetSuccess() *JobStatus {
	if !p.IsSetSuccess() {
		return CloudScootKillJobResult_Success_DEFAULT
	}
	return p.Success
}

var CloudScootKillJobResult_Ir_DEFAULT *InvalidRequest

func (p *CloudScootKillJobResult) GetIr() *InvalidRequest {
	if !p.IsSetIr() {
		return CloudScootKillJobResult_Ir_DEFAULT
	}
	return p.Ir
}

var CloudScootKillJobResult_Err_DEFAULT *ScootServerError

func (p *CloudScootKillJobResult) GetErr() *ScootServerError {
	if !p.IsSetErr() {
		return CloudScootKillJobResult_Err_DEFAULT
	}
	return p.Err
}
func (p *CloudScootKillJobResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CloudScootKillJobResult) IsSetIr() bool {
	return p.Ir != nil
}

func (p *CloudScootKillJobResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *CloudScootKillJobResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.readField0(iprot); err != nil {
				return err
			}
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootKillJobResult) readField0(iprot thrift.TProtocol) error {
	p.Success = &JobStatus{}
	if err := p.Success.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *CloudScootKillJobResult) readField1(iprot thrift.TProtocol) error {
	p.Ir = &InvalidRequest{}
	if err := p.Ir.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Ir), err)
	}
	return nil
}

func (p *CloudScootKillJobResult) readField2(iprot thrift.TProtocol) error {
	p.Err = &ScootServerError{}
	if err := p.Err.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Err), err)
	}
	return nil
}

func (p *CloudScootKillJobResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("KillJob_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootKillJobResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *CloudScootKillJobResult) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetIr() {
		if err := oprot.WriteFieldBegin("ir", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ir: ", p), err)
		}
		if err := p.Ir.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Ir), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ir: ", p), err)
		}
	}
	return err
}

func (p *CloudScootKillJobResult) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetErr() {
		if err := oprot.WriteFieldBegin("err", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:err: ", p), err)
		}
		if err := p.Err.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Err), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:err: ", p), err)
		}
	}
	return err
}

func (p *CloudScootKillJobResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootKillJobResult(%+v)", *p)
}

// Attributes:
//  - Req
type CloudScootOfflineWorkerArgs struct {
	Req *OfflineWorkerReq `thrift:"req,1" json:"req"`
}

func NewCloudScootOfflineWorkerArgs() *CloudScootOfflineWorkerArgs {
	return &CloudScootOfflineWorkerArgs{}
}

var CloudScootOfflineWorkerArgs_Req_DEFAULT *OfflineWorkerReq

func (p *CloudScootOfflineWorkerArgs) GetReq() *OfflineWorkerReq {
	if !p.IsSetReq() {
		return CloudScootOfflineWorkerArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CloudScootOfflineWorkerArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CloudScootOfflineWorkerArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootOfflineWorkerArgs) readField1(iprot thrift.TProtocol) error {
	p.Req = &OfflineWorkerReq{}
	if err := p.Req.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
	}
	return nil
}

func (p *CloudScootOfflineWorkerArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("OfflineWorker_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootOfflineWorkerArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err)
	}
	if err := p.Req.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err)
	}
	return err
}

func (p *CloudScootOfflineWorkerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootOfflineWorkerArgs(%+v)", *p)
}

// Attributes:
//  - Ir
//  - Err
type CloudScootOfflineWorkerResult struct {
	Ir  *InvalidRequest   `thrift:"ir,1" json:"ir,omitempty"`
	Err *ScootServerError `thrift:"err,2" json:"err,omitempty"`
}

func NewCloudScootOfflineWorkerResult() *CloudScootOfflineWorkerResult {
	return &CloudScootOfflineWorkerResult{}
}

var CloudScootOfflineWorkerResult_Ir_DEFAULT *InvalidRequest

func (p *CloudScootOfflineWorkerResult) GetIr() *InvalidRequest {
	if !p.IsSetIr() {
		return CloudScootOfflineWorkerResult_Ir_DEFAULT
	}
	return p.Ir
}

var CloudScootOfflineWorkerResult_Err_DEFAULT *ScootServerError

func (p *CloudScootOfflineWorkerResult) GetErr() *ScootServerError {
	if !p.IsSetErr() {
		return CloudScootOfflineWorkerResult_Err_DEFAULT
	}
	return p.Err
}
func (p *CloudScootOfflineWorkerResult) IsSetIr() bool {
	return p.Ir != nil
}

func (p *CloudScootOfflineWorkerResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *CloudScootOfflineWorkerResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootOfflineWorkerResult) readField1(iprot thrift.TProtocol) error {
	p.Ir = &InvalidRequest{}
	if err := p.Ir.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Ir), err)
	}
	return nil
}

func (p *CloudScootOfflineWorkerResult) readField2(iprot thrift.TProtocol) error {
	p.Err = &ScootServerError{}
	if err := p.Err.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Err), err)
	}
	return nil
}

func (p *CloudScootOfflineWorkerResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("OfflineWorker_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootOfflineWorkerResult) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetIr() {
		if err := oprot.WriteFieldBegin("ir", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ir: ", p), err)
		}
		if err := p.Ir.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Ir), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ir: ", p), err)
		}
	}
	return err
}

func (p *CloudScootOfflineWorkerResult) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetErr() {
		if err := oprot.WriteFieldBegin("err", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:err: ", p), err)
		}
		if err := p.Err.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Err), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:err: ", p), err)
		}
	}
	return err
}

func (p *CloudScootOfflineWorkerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootOfflineWorkerResult(%+v)", *p)
}

// Attributes:
//  - Req
type CloudScootReinstateWorkerArgs struct {
	Req *ReinstateWorkerReq `thrift:"req,1" json:"req"`
}

func NewCloudScootReinstateWorkerArgs() *CloudScootReinstateWorkerArgs {
	return &CloudScootReinstateWorkerArgs{}
}

var CloudScootReinstateWorkerArgs_Req_DEFAULT *ReinstateWorkerReq

func (p *CloudScootReinstateWorkerArgs) GetReq() *ReinstateWorkerReq {
	if !p.IsSetReq() {
		return CloudScootReinstateWorkerArgs_Req_DEFAULT
	}
	return p.Req
}
func (p *CloudScootReinstateWorkerArgs) IsSetReq() bool {
	return p.Req != nil
}

func (p *CloudScootReinstateWorkerArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootReinstateWorkerArgs) readField1(iprot thrift.TProtocol) error {
	p.Req = &ReinstateWorkerReq{}
	if err := p.Req.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Req), err)
	}
	return nil
}

func (p *CloudScootReinstateWorkerArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ReinstateWorker_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootReinstateWorkerArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("req", thrift.STRUCT, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:req: ", p), err)
	}
	if err := p.Req.Write(oprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Req), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:req: ", p), err)
	}
	return err
}

func (p *CloudScootReinstateWorkerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootReinstateWorkerArgs(%+v)", *p)
}

// Attributes:
//  - Ir
//  - Err
type CloudScootReinstateWorkerResult struct {
	Ir  *InvalidRequest   `thrift:"ir,1" json:"ir,omitempty"`
	Err *ScootServerError `thrift:"err,2" json:"err,omitempty"`
}

func NewCloudScootReinstateWorkerResult() *CloudScootReinstateWorkerResult {
	return &CloudScootReinstateWorkerResult{}
}

var CloudScootReinstateWorkerResult_Ir_DEFAULT *InvalidRequest

func (p *CloudScootReinstateWorkerResult) GetIr() *InvalidRequest {
	if !p.IsSetIr() {
		return CloudScootReinstateWorkerResult_Ir_DEFAULT
	}
	return p.Ir
}

var CloudScootReinstateWorkerResult_Err_DEFAULT *ScootServerError

func (p *CloudScootReinstateWorkerResult) GetErr() *ScootServerError {
	if !p.IsSetErr() {
		return CloudScootReinstateWorkerResult_Err_DEFAULT
	}
	return p.Err
}
func (p *CloudScootReinstateWorkerResult) IsSetIr() bool {
	return p.Ir != nil
}

func (p *CloudScootReinstateWorkerResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *CloudScootReinstateWorkerResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootReinstateWorkerResult) readField1(iprot thrift.TProtocol) error {
	p.Ir = &InvalidRequest{}
	if err := p.Ir.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Ir), err)
	}
	return nil
}

func (p *CloudScootReinstateWorkerResult) readField2(iprot thrift.TProtocol) error {
	p.Err = &ScootServerError{}
	if err := p.Err.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Err), err)
	}
	return nil
}

func (p *CloudScootReinstateWorkerResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ReinstateWorker_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootReinstateWorkerResult) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetIr() {
		if err := oprot.WriteFieldBegin("ir", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ir: ", p), err)
		}
		if err := p.Ir.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Ir), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ir: ", p), err)
		}
	}
	return err
}

func (p *CloudScootReinstateWorkerResult) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetErr() {
		if err := oprot.WriteFieldBegin("err", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:err: ", p), err)
		}
		if err := p.Err.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Err), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:err: ", p), err)
		}
	}
	return err
}

func (p *CloudScootReinstateWorkerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootReinstateWorkerResult(%+v)", *p)
}

type CloudScootGetSchedulerStatusArgs struct {
}

func NewCloudScootGetSchedulerStatusArgs() *CloudScootGetSchedulerStatusArgs {
	return &CloudScootGetSchedulerStatusArgs{}
}

func (p *CloudScootGetSchedulerStatusArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		if err := iprot.Skip(fieldTypeId); err != nil {
			return err
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootGetSchedulerStatusArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetSchedulerStatus_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootGetSchedulerStatusArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootGetSchedulerStatusArgs(%+v)", *p)
}

// Attributes:
//  - Success
//  - Err
type CloudScootGetSchedulerStatusResult struct {
	Success *SchedulerStatus  `thrift:"success,0" json:"success,omitempty"`
	Err     *ScootServerError `thrift:"err,1" json:"err,omitempty"`
}

func NewCloudScootGetSchedulerStatusResult() *CloudScootGetSchedulerStatusResult {
	return &CloudScootGetSchedulerStatusResult{}
}

var CloudScootGetSchedulerStatusResult_Success_DEFAULT *SchedulerStatus

func (p *CloudScootGetSchedulerStatusResult) GetSuccess() *SchedulerStatus {
	if !p.IsSetSuccess() {
		return CloudScootGetSchedulerStatusResult_Success_DEFAULT
	}
	return p.Success
}

var CloudScootGetSchedulerStatusResult_Err_DEFAULT *ScootServerError

func (p *CloudScootGetSchedulerStatusResult) GetErr() *ScootServerError {
	if !p.IsSetErr() {
		return CloudScootGetSchedulerStatusResult_Err_DEFAULT
	}
	return p.Err
}
func (p *CloudScootGetSchedulerStatusResult) IsSetSuccess() bool {
	return p.Success != nil
}

func (p *CloudScootGetSchedulerStatusResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *CloudScootGetSchedulerStatusResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 0:
			if err := p.readField0(iprot); err != nil {
				return err
			}
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootGetSchedulerStatusResult) readField0(iprot thrift.TProtocol) error {
	p.Success = &SchedulerStatus{}
	if err := p.Success.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Success), err)
	}
	return nil
}

func (p *CloudScootGetSchedulerStatusResult) readField1(iprot thrift.TProtocol) error {
	p.Err = &ScootServerError{}
	if err := p.Err.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Err), err)
	}
	return nil
}

func (p *CloudScootGetSchedulerStatusResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("GetSchedulerStatus_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField0(oprot); err != nil {
		return err
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootGetSchedulerStatusResult) writeField0(oprot thrift.TProtocol) (err error) {
	if p.IsSetSuccess() {
		if err := oprot.WriteFieldBegin("success", thrift.STRUCT, 0); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 0:success: ", p), err)
		}
		if err := p.Success.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Success), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 0:success: ", p), err)
		}
	}
	return err
}

func (p *CloudScootGetSchedulerStatusResult) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetErr() {
		if err := oprot.WriteFieldBegin("err", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:err: ", p), err)
		}
		if err := p.Err.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Err), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:err: ", p), err)
		}
	}
	return err
}

func (p *CloudScootGetSchedulerStatusResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootGetSchedulerStatusResult(%+v)", *p)
}

// Attributes:
//  - MaxTasks
type CloudScootThrottleSchedulerArgs struct {
	MaxTasks int32 `thrift:"maxTasks,1" json:"maxTasks"`
}

func NewCloudScootThrottleSchedulerArgs() *CloudScootThrottleSchedulerArgs {
	return &CloudScootThrottleSchedulerArgs{}
}

func (p *CloudScootThrottleSchedulerArgs) GetMaxTasks() int32 {
	return p.MaxTasks
}
func (p *CloudScootThrottleSchedulerArgs) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootThrottleSchedulerArgs) readField1(iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.MaxTasks = v
	}
	return nil
}

func (p *CloudScootThrottleSchedulerArgs) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ThrottleScheduler_args"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootThrottleSchedulerArgs) writeField1(oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin("maxTasks", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:maxTasks: ", p), err)
	}
	if err := oprot.WriteI32(int32(p.MaxTasks)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.maxTasks (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:maxTasks: ", p), err)
	}
	return err
}

func (p *CloudScootThrottleSchedulerArgs) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootThrottleSchedulerArgs(%+v)", *p)
}

// Attributes:
//  - Ir
//  - Err
type CloudScootThrottleSchedulerResult struct {
	Ir  *InvalidRequest   `thrift:"ir,1" json:"ir,omitempty"`
	Err *ScootServerError `thrift:"err,2" json:"err,omitempty"`
}

func NewCloudScootThrottleSchedulerResult() *CloudScootThrottleSchedulerResult {
	return &CloudScootThrottleSchedulerResult{}
}

var CloudScootThrottleSchedulerResult_Ir_DEFAULT *InvalidRequest

func (p *CloudScootThrottleSchedulerResult) GetIr() *InvalidRequest {
	if !p.IsSetIr() {
		return CloudScootThrottleSchedulerResult_Ir_DEFAULT
	}
	return p.Ir
}

var CloudScootThrottleSchedulerResult_Err_DEFAULT *ScootServerError

func (p *CloudScootThrottleSchedulerResult) GetErr() *ScootServerError {
	if !p.IsSetErr() {
		return CloudScootThrottleSchedulerResult_Err_DEFAULT
	}
	return p.Err
}
func (p *CloudScootThrottleSchedulerResult) IsSetIr() bool {
	return p.Ir != nil
}

func (p *CloudScootThrottleSchedulerResult) IsSetErr() bool {
	return p.Err != nil
}

func (p *CloudScootThrottleSchedulerResult) Read(iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}

	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin()
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if err := p.readField1(iprot); err != nil {
				return err
			}
		case 2:
			if err := p.readField2(iprot); err != nil {
				return err
			}
		default:
			if err := iprot.Skip(fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *CloudScootThrottleSchedulerResult) readField1(iprot thrift.TProtocol) error {
	p.Ir = &InvalidRequest{}
	if err := p.Ir.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Ir), err)
	}
	return nil
}

func (p *CloudScootThrottleSchedulerResult) readField2(iprot thrift.TProtocol) error {
	p.Err = &ScootServerError{}
	if err := p.Err.Read(iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.Err), err)
	}
	return nil
}

func (p *CloudScootThrottleSchedulerResult) Write(oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin("ThrottleScheduler_result"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if err := p.writeField1(oprot); err != nil {
		return err
	}
	if err := p.writeField2(oprot); err != nil {
		return err
	}
	if err := oprot.WriteFieldStop(); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *CloudScootThrottleSchedulerResult) writeField1(oprot thrift.TProtocol) (err error) {
	if p.IsSetIr() {
		if err := oprot.WriteFieldBegin("ir", thrift.STRUCT, 1); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:ir: ", p), err)
		}
		if err := p.Ir.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Ir), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 1:ir: ", p), err)
		}
	}
	return err
}

func (p *CloudScootThrottleSchedulerResult) writeField2(oprot thrift.TProtocol) (err error) {
	if p.IsSetErr() {
		if err := oprot.WriteFieldBegin("err", thrift.STRUCT, 2); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:err: ", p), err)
		}
		if err := p.Err.Write(oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.Err), err)
		}
		if err := oprot.WriteFieldEnd(); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 2:err: ", p), err)
		}
	}
	return err
}

func (p *CloudScootThrottleSchedulerResult) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("CloudScootThrottleSchedulerResult(%+v)", *p)
}
