// Automatically generated by MockGen. DO NOT EDIT!
// Source: cluster.go

package cluster_membership

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Cluster interface
type MockCluster struct {
	ctrl     *gomock.Controller
	recorder *_MockClusterRecorder
}

// Recorder for MockCluster (not exported)
type _MockClusterRecorder struct {
	mock *MockCluster
}

func NewMockCluster(ctrl *gomock.Controller) *MockCluster {
	mock := &MockCluster{ctrl: ctrl}
	mock.recorder = &_MockClusterRecorder{mock}
	return mock
}

func (_m *MockCluster) EXPECT() *_MockClusterRecorder {
	return _m.recorder
}

func (_m *MockCluster) Members() []Node {
	ret := _m.ctrl.Call(_m, "Members")
	ret0, _ := ret[0].([]Node)
	return ret0
}

func (_mr *_MockClusterRecorder) Members() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Members")
}
